In [2]:
import tensorflow as tf

# Turning numpy arrays to tensors

In [3]:
import numpy as np 
numpy_A=np.arange(1,25,dtype=np.int32) #Create a numpy array between 1 and 25

tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [4]:
A=tf.constant(value=numpy_A, dtype=tf.int32, shape=(2,3,4))

In [5]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>