# Finding positinal max and min of a tensor

🔹 tf.argmax() — for max position

🔹 tf.argmin() — for min position

In [3]:
# Create a new tensor for finding positional min and max
import tensorflow as tf 

tf.random.set_seed(10)
tensor=tf.random.uniform(shape=[50])

tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.644151  , 0.8082472 , 0.8976548 , 0.6368902 , 0.6270969 ,
       0.9936013 , 0.02359486, 0.03668392, 0.5860578 , 0.5740315 ,
       0.09047401, 0.5755553 , 0.25272822, 0.11045039, 0.61225283,
       0.1290685 , 0.89660144, 0.06479812, 0.8622047 , 0.82242084,
       0.4016037 , 0.7659943 , 0.4539342 , 0.32376182, 0.4617684 ,
       0.32858098, 0.8104389 , 0.1609515 , 0.07981062, 0.5934839 ,
       0.6243702 , 0.9112947 , 0.88744843, 0.9568223 , 0.436625  ,
       0.9997524 , 0.24064243, 0.8281152 , 0.54077435, 0.8436167 ,
       0.33806038, 0.9431902 , 0.08632314, 0.68907607, 0.53072953,
       0.9125186 , 0.06304038, 0.95265174, 0.8152896 , 0.57640743],
      dtype=float32)>

In [4]:
# finding the positional maximum

tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [ ]:
# for checking 
max(tensor),tf.reduce_max(tensor)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9997524>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9997524>)

In [6]:
# finding the positional minimum
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=6>

In [8]:
# For checking 
min(tensor),tf.reduce_min(tensor)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.023594856>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.023594856>)

In [9]:
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.644151  , 0.8082472 , 0.8976548 , 0.6368902 , 0.6270969 ,
       0.9936013 , 0.02359486, 0.03668392, 0.5860578 , 0.5740315 ,
       0.09047401, 0.5755553 , 0.25272822, 0.11045039, 0.61225283,
       0.1290685 , 0.89660144, 0.06479812, 0.8622047 , 0.82242084,
       0.4016037 , 0.7659943 , 0.4539342 , 0.32376182, 0.4617684 ,
       0.32858098, 0.8104389 , 0.1609515 , 0.07981062, 0.5934839 ,
       0.6243702 , 0.9112947 , 0.88744843, 0.9568223 , 0.436625  ,
       0.9997524 , 0.24064243, 0.8281152 , 0.54077435, 0.8436167 ,
       0.33806038, 0.9431902 , 0.08632314, 0.68907607, 0.53072953,
       0.9125186 , 0.06304038, 0.95265174, 0.8152896 , 0.57640743],
      dtype=float32)>

In [10]:
# Finding the min value using argin min index
tensor[6]

<tf.Tensor: shape=(), dtype=float32, numpy=0.023594856>

In [11]:
# Similarly finding max value using argmax index
tensor[35]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9997524>