In [1]:
import tensorflow as tf

# Creating random tensors

In [2]:
random_tensor=tf.random.uniform(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.41809726, 0.7713686 ],
       [0.51398504, 0.925365  ],
       [0.06742084, 0.47254312]], dtype=float32)>

In [3]:
# create a random tensor
#tf.random.set_seed(42) # set seed for reproducibility
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.uniform(shape=(3,2))

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.uniform(shape=(3,2))

random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [4]:
tf.random.set_seed(42)
random_3=tf.random.uniform(shape=(3,2))
tf.random.set_seed(42)
random_4=tf.random.uniform(shape=(3,2))
random_3, random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678],
        [0.3528825 , 0.46448255],
        [0.03366041, 0.68467236]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678],
        [0.3528825 , 0.46448255],
        [0.03366041, 0.68467236]], dtype=float32)>)