In [1]:
import tensorflow as tf

# Shuffle the order of elements in a tensor

In [2]:
not_shuffled=tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9]])


not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [3]:
# shuffle a tensor (valuable for when you want to shuffle your data)
shuffled_tensor=tf.random.shuffle(not_shuffled)
shuffled_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])>

In [4]:
tf.random.set_seed(42)  # global level random seed
tf.random.shuffle(not_shuffled,seed=42)  # operational level random seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>