# trying out more tensor math operations

In [1]:
import tensorflow as tf

In [3]:
tensor= tf.range(10)  # Creates a 1D tensor with values from 0 to 9

tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [6]:
# Square the tensor

tf.square(tensor)  # Squares each element in the tensor

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [10]:
# will raise an error if tensor is int
# tf.sqrt(tensor)  # Computes the square root of each element in the tensor

In [9]:
tf.sqrt(tf.cast(tensor,dtype=tf.float16))  # Computes the square root of each element in the tensor

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [13]:
# finding the log 
tf.math.log(tf.cast(tensor,dtype=tf.float16)) 

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 ], dtype=float16)>

In [16]:
# Computes the sine of each element in the tensor
tf.sin(tf.cast(tensor,dtype=tf.float16))  # Computes the sine of each element in the tensor

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([ 0.    ,  0.8413,  0.909 ,  0.1411, -0.757 , -0.959 , -0.2793,
        0.657 ,  0.9893,  0.412 ], dtype=float16)>

In [17]:
# Computes the cosine of each element in the tensor
tf.cos(tf.cast(tensor,dtype=tf.float16))  # Computes the cosine of each element in the tensor

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([ 1.    ,  0.5405, -0.4163, -0.99  , -0.654 ,  0.2837,  0.96  ,
        0.754 , -0.1455, -0.911 ], dtype=float16)>