# Aggregating tensors

### **Tensor aggregation** is the process of combining multiple tensor values into a single tensor using operations like sum, mean, or concatenation.


In [1]:
import tensorflow as tf

In [2]:
# get the absolute  value

tensor=tf.constant([-7,-10])

tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [3]:
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

# Element-wise aggregation

#### Aggregating values across dimensions using operations like:

* sum(): Sum all or specific dimensions.

* mean(): Average values along certain axes.

* max() / min(): Find maximum/minimum values.

In [4]:
# Create a tensor with random values between 1 to 100 of size 50
import numpy as np 
np_arr=np.random.randint(low=1,high=100,size=50)
tensor=tf.constant(np_arr)

tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([45, 55,  7, 32, 94, 38, 86, 65, 74,  5, 20, 92, 12,  5, 68, 73, 42,
       97, 65, 98, 22, 66, 77, 90, 11, 62, 97,  1, 27, 51, 69, 36, 35, 77,
       14, 88,  2, 70, 91, 34,  6, 16,  5, 14, 60, 27, 77,  5, 85, 50])>

In [5]:
tensor.shape,tensor.ndim,tf.size(tensor)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [6]:
# finding the minimum
tf.reduce_min(input_tensor=tensor,name="min value in tensor ## optional")

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [7]:
# finding maximu 
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [8]:
#finding the mean 
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=48>

In [9]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2438>

In [10]:
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([45, 55,  7, 32, 94, 38, 86, 65, 74,  5, 20, 92, 12,  5, 68, 73, 42,
       97, 65, 98, 22, 66, 77, 90, 11, 62, 97,  1, 27, 51, 69, 36, 35, 77,
       14, 88,  2, 70, 91, 34,  6, 16,  5, 14, 60, 27, 77,  5, 85, 50])>

In [11]:
a = tf.constant([[1, 2]])
b = tf.constant([[3, 4]])

tf.concat([a,b],axis=0)  

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [12]:
tf.stack([a,b],axis=0)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]])>



### 🔹 `tf.concat`: **Joins tensors along an existing axis**

* **Does not add a new dimension**
* Requires tensors to have the **same shape except** along the concatenation axis.

### 🔹 `tf.stack`: **Stacks tensors along a new axis**

* **Adds a new dimension**
* Requires all tensors to have **exactly the same shape**

### ✅ Summary

| Operation   | Adds new dimension? | Output shape (for a, b shape (1, 2)) |
| ----------- | ------------------- | ------------------------------------ |
| `tf.concat` | ❌ No                | `(2, 2)`                             |
| `tf.stack`  | ✅ Yes               | `(2, 1, 2)`                          |

Use:

* `concat` when you want to **combine** tensors *without changing the rank*.
* `stack` when you want to **group** tensors into a higher-dimensional tensor.


In [20]:
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([45, 55,  7, 32, 94, 38, 86, 65, 74,  5, 20, 92, 12,  5, 68, 73, 42,
       97, 65, 98, 22, 66, 77, 90, 11, 62, 97,  1, 27, 51, 69, 36, 35, 77,
       14, 88,  2, 70, 91, 34,  6, 16,  5, 14, 60, 27, 77,  5, 85, 50])>

In [21]:
float_tensor=tf.cast(x=tensor,dtype=tf.float16)

float_tensor

<tf.Tensor: shape=(50,), dtype=float16, numpy=
array([45., 55.,  7., 32., 94., 38., 86., 65., 74.,  5., 20., 92., 12.,
        5., 68., 73., 42., 97., 65., 98., 22., 66., 77., 90., 11., 62.,
       97.,  1., 27., 51., 69., 36., 35., 77., 14., 88.,  2., 70., 91.,
       34.,  6., 16.,  5., 14., 60., 27., 77.,  5., 85., 50.],
      dtype=float16)>

In [22]:
tf.math.reduce_std(float_tensor)

<tf.Tensor: shape=(), dtype=float16, numpy=31.7>

In [23]:
tf.math.reduce_variance(float_tensor)

<tf.Tensor: shape=(), dtype=float16, numpy=1005.0>