# Manupulating tensors (Tensor Operations)
## Basic Operation

* `+`
* `-`
* `*`
* `/`

In [1]:
import tensorflow as tf

In [2]:
tensor=tf.constant([[1,2],[3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [3]:
# Adding a number to a tensor
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]])>

In [4]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [6]:
# Subtracting a number from a tensor
tensor - 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]])>

In [7]:
# multiplying a tensor by a number
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [8]:
# dividing a tensor by a number
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.1, 0.2],
       [0.3, 0.4]])>

In [9]:
# we can use tf built in functions to do the same operations
tf.add(tensor, 10), tf.subtract(tensor, 10), tf.multiply(tensor, 10), tf.divide(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-9, -8],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1, 0.2],
        [0.3, 0.4]])>)

In [10]:
tf.math.add(tensor, 10), tf.math.subtract(tensor, 10), tf.math.multiply(tensor, 10), tf.math.divide(tensor, 10)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[-9, -8],
        [-7, -6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]])>,
 <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
 array([[0.1, 0.2],
        [0.3, 0.4]])>)

In [11]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>