In [1]:
import tensorflow as tf

# Other way to make tensors

In [2]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [3]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [4]:
tf.ones(shape=(3,2), dtype=tf.int16)

<tf.Tensor: shape=(3, 2), dtype=int16, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)>