# Tensors and Numpy 

## Why this is powerful:
NumPy = fast, flexible data handling

TensorFlow = powerful modeling + GPU acceleration

They work together seamlessly — no need to manually convert formats most of the time

In [3]:
import tensorflow as tf
import numpy as np

In [5]:
# Create a tensor directly from a numpy array 

np_array=np.array([[1,2,3],[4,5,6]])

tensor=tf.Variable(np_array)

tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
np_arr = np.array([1, 2, 3, 4])
tf_tensor = tf.convert_to_tensor(np_arr)

print("Tensor:", tf_tensor)

Tensor: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [8]:
# Converts a tensor to a numpy array

np.array(tensor) , type(np.array(tensor))

(array(<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>, dtype=object),
 numpy.ndarray)

In [9]:
result = tf_tensor * 2       # TensorFlow operation
np_result = result.numpy()   # Back to NumPy

print("NumPy result:", np_result)

NumPy result: [2 4 6 8]


In [10]:
tensor = tf.constant([[1, 2], [3, 4]])

tensor.numpy()  # Converts the tensor to a NumPy array

array([[1, 2],
       [3, 4]])

# ✅ Use NumPy for preprocessing, TensorFlow for modeling

In [11]:
# NumPy for normalizing data
data = np.random.rand(5, 3) * 100
normalized = (data - np.mean(data)) / np.std(data)

# Feed into TensorFlow
tf_input = tf.convert_to_tensor(normalized, dtype=tf.float32)
print(tf_input)

tf.Tensor(
[[ 0.64084023  0.34748086  0.30095583]
 [-0.7786505   0.7654589  -1.5540342 ]
 [ 0.28603482  0.3858939   0.73297703]
 [-0.52104264  1.2874637   1.4622967 ]
 [ 0.07618804 -1.5731565  -1.8587061 ]], shape=(5, 3), dtype=float32)


# ✅ Slicing and reshaping using NumPy and TensorFlow together

In [12]:
a = np.arange(12).reshape(3, 4)  # NumPy reshape
t = tf.convert_to_tensor(a)

# TensorFlow slicing
print(t[:, 1:3])

tf.Tensor(
[[ 1  2]
 [ 5  6]
 [ 9 10]], shape=(3, 2), dtype=int32)


# ✅ Training with NumPy data in a TensorFlow model

In [13]:
# NumPy data
x = np.random.rand(100, 1)
y = 3 * x + 2

# TensorFlow model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=3) 

Epoch 1/3
4/4 [==============================] - 0s 1ms/step - loss: 12.2811
Epoch 2/3
4/4 [==============================] - 0s 997us/step - loss: 12.2372
Epoch 3/3
4/4 [==============================] - 0s 749us/step - loss: 12.1938
