# Getting Information from the Tensor

### Few imporatant attributes
* Shape
* Rank
* Axis or dimension
* size

In [1]:
import tensorflow as tf 

In [3]:
# Create a Rank  4 tensor 
rank_4_tensor=tf.ones(shape=[2,3,4,5])

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [4]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [7]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor), rank_4_tensor.dtype

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>,
 tf.float32)

In [8]:
2*3*4*5

120

In [13]:
# Various attributes of our tensor
print("Shape of tensor:", rank_4_tensor.shape)
print("Rank of tensor:", rank_4_tensor.ndim)
print("Total number of elements in tensor:", tf.size(rank_4_tensor).numpy())
print("Data type of tensor:", rank_4_tensor.dtype)
print("Shape of Elements in the first dimension:", rank_4_tensor.shape[0])
print("Shape of Elements in the last dimension:", rank_4_tensor.shape[-1])

Shape of tensor: (2, 3, 4, 5)
Rank of tensor: 4
Total number of elements in tensor: 120
Data type of tensor: <dtype: 'float32'>
Shape of Elements in the first dimension: 2
Shape of Elements in the last dimension: 5


| Attribute         | What it tells you                     | Example output       |
| ----------------- | ------------------------------------- | -------------------- |
| `tensor.shape`    | Shape (dimensions)                    | `(2, 3, 4)`          |
| `tensor.ndim`     | Number of dimensions (rank)           | `3`                  |
| `tf.size(tensor)` | Total number of elements              | `24`                 |
| `tensor.dtype`    | Data type of elements                 | `tf.float32`         |
| `tensor.device`   | Device it's stored on                 | `/CPU:0` or `/GPU:0` |
| `tensor.numpy()`  | Convert to NumPy / Python native type | `np.ndarray`         |
