In [1]:
import tensorflow as tf

print(tf.__version__)

2.3.0


# Creating tensors with tf.constant()

In [4]:
# Creating the scaler
scalar=tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
scalar.ndim

0

In [6]:
# Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
vector.ndim

1

In [8]:
# create a matrix (has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [10]:
# create a another matrix
another_matrix=tf.constant([[10.,7.],
                              [7.,10.],
                              [10.,7.]],dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [10.,  7.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# Lets create a tensor with shape (3,2,3)
tensor_3d=tf.constant([[[1,2,3],
                        [4,5,6]],
                        
                        [[7,8,9],
                         [10,11,12]],
                        [[13,14,15],
                         [16,17,18]]])
tensor_3d

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tensor_3d.ndim

3